[package]
name = "min_dist_method"
version = "0.1.0"
authors = ["knzkhuka <one235813@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
csv = "1.1"
gnuplot = "0.0.37"