[package]
name = "k_means"
version = "0.1.0"
authors = ["knzkhuka <one235813@gmai.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
csv = "1.1"
gnuplot = "0.0.37"